### ISSUE TITLE
Support child props

### ISSUE THREAD

**Issue by testshallpass** [testshallpass/react-native-simple-stepper#2]

**Comment by peteleco** [comment]
Hi, i implemented a stepper using component instead images. And i use yours as inspiration.

[react-native-stepper](https://github.com/peteleco/react-native-stepper/blob/master/readme.md)

**Comment by devBrian** [comment]
hi @peteleco. That's awesome and a good idea. 👍  But what if the component is not included in the class. For instance, the class's import does not include Icon, Image, etc. Would it not throw an error saying could not find 'XYZ'?

**Comment by peteleco** [comment]
No, the <Icon> in the example its been imported in the file that i'm using the <Stepper>

**Comment by devBrian** [comment]
True, so the parent takes care of it's child. Good stuff.

**Comment by devbriguy** [comment]
Component prop is a good idea but it would be different from iOS UIStepper control which only accepts an image.

**Comment by testshallpass** [comment]
Add render props #10 takes care of this.
