### ISSUE TITLE
Typescript type declaration warning.

### ISSUE THREAD

**Issue by tudorelu** [testshallpass/react-native-simple-stepper#31]
Hey bro, thanks for making this component - I am using it in an app that I'm building.
I encountered this annoying warning when using in typescript environment:

<img width="789" alt="rnstepper_ts_warning" src="https://user-images.githubusercontent.com/10128444/85087967-41281700-b222-11ea-87de-5638c6155d54.png">

I temporarily fixed it by adding an `index.d.ts` file containing 
```javascript 
declare module 'react-native-simple-stepper';
```  
I'm not sure what the process of updating a package to be 'typescript friendly' is, but I don't think it's a lot more than this for this repo (I might be wrong tho). Might be worth doing...  I would be happy contribute it if you don't have the time.

<img width="908" alt="rn-stepper-ts-fix" src="https://user-images.githubusercontent.com/10128444/85088666-ff986b80-b223-11ea-95a6-cbdc05a0e53e.png">

**Comment by testshallpass** [comment]
I shall add typescript definitions in the future. I definitely think it is helpful.

**Comment by testshallpass** [comment]
I have added them, see PR #36, thanks.
