### ISSUE TITLE
Annoying 'Invalid argument supplid to oneOfType' warning.

### ISSUE THREAD

**Issue by tudorelu** [testshallpass/react-native-simple-stepper#32]
Hey again Brian,

Using the SimpleStepper component in a typescript environment and trying to change some of it's styling like in the picture below:
<img width="605" alt="rn-ss-comp" src="https://user-images.githubusercontent.com/10128444/85089617-6cad0080-b226-11ea-9da0-9a1cb8875cae.png">
I encounter a warning which I suspect has something to do with TypeScript: 
**Warning: Invalid argument supplid to oneOfType. Expected an array of check functions, but received string at index 0.**
<img width="933" alt="rn-ss-warning" src="https://user-images.githubusercontent.com/10128444/85089955-4c317600-b227-11ea-99df-c980dab7453b.png">
The line that it references is line 44 here:
<img width="1075" alt="rn-ss-warning-line" src="https://user-images.githubusercontent.com/10128444/85089892-1d1b0480-b227-11ea-86ed-61c494489fa4.png">

I have no idea how one would tackle this... Would appreciate your help here.

**Comment by limaho** [comment]
I am having same issue. @tudorelu did you solve it?

**Comment by jossydeleon** [comment]
@limaho @tudorelu on SimpleStepper.js line 45 use Proptypes.oneOf instead of oneOfType. PropTypes.oneOf is a simple enum of literal values that has to match one of these exact values. Proptypes.oneOfType means enumerating the types of values that your component can accept.

**Comment by testshallpass** [comment]
I have plans to add typescript definitions and I will take a closer look at this case.

**Comment by tudorelu** [comment]
Thanks @testshallpass. @jossydeleon that worked mate, removed the warning!

**Comment by testshallpass** [comment]
PR #33 merged and released v3.0.2. Also, have PR #36 ready, please review. Thanks.
