### ISSUE TITLE
Is value expected with initial value 0.05?

### ISSUE THREAD

**Issue by WangJian0** [testshallpass/react-native-simple-stepper#4]
Continuous plus or minus the time will be wrong, such as an initial value of 0.05, I added twice after 2.05, when I press the time, his value becomes 1.049999999998.

**Comment by testshallpass** [comment]
Hi @WangJian0 What is your step and min/max values? What do you mean "press the time"?

**Comment by WangJian0** [comment]
Sorry,it's my fault.I mean by min values,but the value changed to 1.049999999998.

**Comment by testshallpass** [comment]
So the when it hits the min value you are saying it changes to 1.049999999998?

**Comment by testshallpass** [comment]
Can you share the step value and the min/max values, so I may try it out?

**Comment by WangJian0** [comment]
initialValue = 0.05
minimumValue={-100}
maximumValue={1000}


and i don't set up stepValue use default value 1;

**Comment by testshallpass** [comment]
@WangJian0  Hi again. I have an easy solution to your question. The value you receive in the `valueChanged` callback is purely a number variable calculated based on value plus or minus stepValue. So the value you got is **correct**. Now that said if you want to display the number at a certain decimal place you can do so as followed: 

```javascript
// ...
valueChanged(value: number) {
    const displayValue = value.toFixed(2)
    //  ... use in state change or other function
    //  ... or round it
    const roundValue = Math.round(value * 100) / 100
}
// ...
```
