### ISSUE TITLE
is it possible to set value for simple stepper?

### ISSUE THREAD

**Issue by WangJian0** [testshallpass/react-native-simple-stepper#5]
I only see the initialValue property, but what if I want update the stepper value ?

Here is the scenario:
I have a text input to work with the simple stepper. and I want to input a number in text input (e.g. 19). Is there a way to set the 19 as the value of stepper ? even the stepper already initialized.

**Comment by testshallpass** [comment]
Hi @WangJian0 If the stepper is already mounted it will not update initialValue prop if you have a state change from text input. I'm happy to fix this. All it takes is using the `componentWillReceiveProps(nextProps)` and do a comparison on the initialValue and update the component accordingly.

**Comment by testshallpass** [comment]
See Allows to change value from outside #7 as it will solve this issue.

**Comment by testshallpass** [comment]
Fixed on 1.11.0
