### ISSUE TITLE
Compatibility with React-Native-Web?

### ISSUE THREAD

**Issue by KjellConnelly** [testshallpass/react-native-simple-stepper#6]
Can we get this to work with React-Native-Web? In its current form, it looks like it needs to be converted to ES5, and tintColor is not a valid css property.

**Comment by testshallpass** [comment]
I welcome a PR. And so ... Wouldn't it need to be merged into React-Native-Web? What other requirements might it need?

**Comment by testshallpass** [comment]
Reopen if you have more info. Thanks.
